# Generated by Django 5.1.6 on 2025-03-09 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_comment_id_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 17, 10, 2, 630159)),
        ),
    ]
